version: "3.3"

services:
  mongo-java-rs:
    image: mongodb-read-test:latest
    container_name: mongodb-read-test
    hostname: mongodb-read-test
    ports:
      - "18080:8080"
      - "19090:19090"
    environment:
     - VIZIX_MONGO_PRIMARY=10.100.0.64:27017
     - VIZIX_MONGO_SSL=false
     - VIZIX_MONGO_USERNAME=admin
     - VIZIX_MONGO_PASSWORD=control123!
     - VIZIX_MONGO_AUTHDB=admin
     - VIZIX_MONGO_CONTROL_READPREFERENCE=primaryPreferred
     - VIZIX_MONGO_REPORTS_READPREFERENCE=secondaryPreferred
     - VIZIX_MONGO_CONNECTION_TIMEOUT=5000
     - VIZIX_MONGO_SOCKET_TIMEOUT=30000
     - VIZIX_MONGO_MAX_POOL_SIZE=100
     - VIZIX_MONGO_MIN_POOL_SIZE=0
     - VIZIX_MONGO_MAX_IDLE_TIME=60000
     - VIZIX_MONGO_DATABASE=riot_main
